### ISSUE TITLE
 Select the target application" is not displayed.

### ISSUE THREAD

**Issue by caesar2015** [Hennamann/ExtendScript-for-Visual-Studio-Code#15]
I'm using a macbook pro (M1 / arm64).

I have installed "ExtendScript" but I don't see "select the target application" on the toolbar.

I tried it on another mac (intel chipset) and it is displayed there.

**Comment by knightvfx** [comment]
I have the same issue, did you manage to solve it?

**Comment by kikili** [comment]
Same issue here on an Intel chipset mac btw.
Also the extension crash and do not load

**Comment by Hennamann** [comment]
This is an issue with the Official Adobe Extendscript debugger extension from Adobe. Not sure of the best way to contact Adobe for this, perhaps the Adobe forums or the CEP resource repository here on github... there is also a beta 2.0 version under NDA prerelease over at Adobeprerelease.com that might fix the issue. 

Anyhow closing this issue since it's not something i can fix.

**Comment by kikili** [comment]
Well, it is displayed when I deactivate your extension.
Also your extension crash at start 5 times and apparently not loaded anymore.

**Comment by kikili** [comment]
Can you tell me in which programme it is available in prerelease. I don't see it ...

**Comment by kikili** [comment]
Found it 👍 https://www.adobeprerelease.com/beta/918068DD-4655-4298-925A-1E6EA4BFA84B
